server:
  port: 8762

spring:
  application:
    name: service-filter
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
